[package]
name = "nai/knit-rpg"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
Component = "sleitnick/component@2.4.5"
Loader = "sleitnick/loader@1.0.2"
Option = "sleitnick/option@1.0.3"
Signal = "sleitnick/signal@1.2.0"
TaskQueue = "sleitnick/task-queue@0.1.0"
Trove = "sleitnick/trove@0.4.1"
Promise = "evaera/promise@4.0.0"
Hitbox = "nightcycle/hitbox@4.1.0"
Timer = "sleitnick/timer@1.1.1"
Input = "sleitnick/input@1.3.2"
Fusion = "elttob/fusion@0.1.1-beta"